name: Bug Report
description: File a bug report to help us improve!
labels: ["bug", "unconfirmed"]
assignees:
  - Valorless
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was supposed to happen?
      placeholder: What is the intended outcome?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How do I reproduce this issue?
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      placeholder: Please copy and paste any relevant console log output. This will be automatically formatted into code.
      render: shell
  - type: input
    id: server_version
    attributes:
      label: Server Version
      description: What spigot or paper version are you using? (run '/version' in-game)
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      description: What version of ValorlessUtils are you using?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Confirmation
      description: Please confirm the following below.
      options:
        - label: I have downloaded and tried the latest version of ValorlessUtils and the issue still persists.
          required: true
        - label: I have provided sufficient information for the issue to be replicated.
          required: true
